name: App CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: latest

    - name: Install dependencies
      run: yarn install && npm install -g codecov

    - name: Run tests
      run: yarn run test

    - name: Upload Codecov reports
      uses: codecov/codecov-action@main
      with:
        fail_ci_if_error: true
        token: ${{ secrets.CODECOV_TOKEN }}
        verbose: true
